### Exercise 1: NumPy array Indexing/Slicing

In [2]:
from si.data.dataset import Dataset
from si.io.csv_file import read_csv
import numpy as np


ModuleNotFoundError: No module named 'si'

In [ ]:
# 1.1 load Iris dataset
iris = read_csv("datasets/iris/iris.csv",features = ("sepal_length","sepal_width","petal_length","petal_width"),label = ("class"))
iris.summary()

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

In [ ]:
 # 1.2 dimension penultimate independent variable
np.ndim(iris.X[-2])

# 1 dimention


1

In [ ]:
# 1.3 tail and mean
iris_tail = iris.X[-10:]
print(iris_tail)

for i in range(0,iris_tail.shape[1]):
    print(iris_tail[:,i])
    print(np.nanmean(iris_tail[:,i]))


[[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
[6.7 6.9 5.8 6.8 6.7 6.7 6.3 6.5 6.2 5.9]
6.450000000000001
[3.1 3.1 2.7 3.2 3.3 3.  2.5 3.  3.4 3. ]
3.0300000000000002
[5.6 5.1 5.1 5.9 5.7 5.2 5.  5.2 5.4 5.1]
5.33
[2.4 2.3 1.9 2.3 2.5 2.3 1.9 2.  2.3 1.8]
2.17


In [ ]:
# 1.4 samples with values <= 6

filtered_samples = iris.X[(iris.X <= 6).all(axis=1)]

print(filtered_samples.shape[0])
#89


89


In [ ]:
# 1.5 labels != iris-setosa
filtered_setosa = iris.X[(iris.y != 'Iris-setosa')]

print(filtered_setosa.shape[0])
#100

100
